services:
  pocketbase:
    image: ghcr.io/buco7854/pocket-crm-backend:latest
    ports:
      - "8090:8090"
    volumes:
      - pb_data:/pb/pb_data
    env_file: .env
    restart: always
    healthcheck:
      test: ["CMD", "wget", "--quiet", "--tries=1", "--spider", "http://localhost:8090/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s

  frontend:
    image: ghcr.io/buco7854/pocket-crm-frontend:latest
    environment:
      - PB_URL
    ports:
      - "80:80"
    depends_on:
      pocketbase:
        condition: service_healthy
    restart: always

volumes:
  pb_data:
    name: pocket_crm_pb_data
